# Generated by Django 4.0 on 2021-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('period', models.IntegerField(default=0)),
                ('reg_no', models.IntegerField(default=0)),
            ],
        ),
    ]
